### ISSUE TITLE
FE - porovnavanie s undefined v html

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/reservation-system#1]
Myslim, ze v html staci namiesto ngIf = title != undefined iba ngIf = title, ked title existuje, berie to ako true

https://github.com/AppsLab-2/reservation-system/blob/e0e2ddf2113175cec086a644192a13121b56d2ec/frontend/src/app/shared/component/header/header.component.html#L1

**Comment by zemcikerik** [comment]
Fixed in latest commit, thanks :smile:
