### ISSUE TITLE
FE - globalna konstanta

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/reservation-system#2]
String 'http://localhost atd' mozte spravit ako globalnu konstantu a uz potom iba v jednotlivych servisach si vytvorit konstanty ako zvysky stringu pre kazdy endpoint. Keby appku niekde nasadite a nemali by ste uz localhost:8080, museli by ste toto menit na vela miestach.

https://github.com/AppsLab-2/reservation-system/blob/e0e2ddf2113175cec086a644192a13121b56d2ec/frontend/src/app/core/service/business.service.ts#L16

**Comment by zemcikerik** [comment]
Fixed in latest commit, thanks :smile:
